### ISSUE TITLE
无法截图：E/Screenshot: Unsupported protocol: 2

### ISSUE THREAD

**Issue by zhujunsan** [microdog/wechat_automated_jump_game#1]
* Windows 10 + Pixel 2 XL@8.1.0

> JPython 已经替换成 FAQ 里写的 2.5.4rc1

* 按回车开始之后报截图错误，日志如下

```
PS D:\Android_sdk\tools> .\monkeyrunner.bat D:\Web\wechat_automated_jump_game\monkeyrunner.py XXXXXXXXXXXXXX http://127.0.0.1:5000
Connecting XXXXXXXXXXXXXX
Connected
Press enter to start
Taking snapshot...
03:27:17 E/Screenshot: Unsupported protocol: 2
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions] Script terminated due to an exception
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]Traceback (most recent call last):
  File "D:\Web\wechat_automated_jump_game\monkeyrunner.py", line 67, in <module>
    main()
  File "D:\Web\wechat_automated_jump_game\monkeyrunner.py", line 29, in main
    img_data = snapshot.convertToBytes('png')
        at com.android.chimpchat.adb.image.ImageUtils.convertImage(ImageUtils.java:47)
        at com.android.chimpchat.adb.image.ImageUtils.convertImage(ImageUtils.java:63)
        at com.android.chimpchat.adb.AdbChimpImage.createBufferedImage(AdbChimpImage.java:41)
        at com.android.chimpchat.core.ChimpImageBase.getBufferedImage(ChimpImageBase.java:65)
        at com.android.chimpchat.core.ChimpImageBase.convertSnapshot(ChimpImageBase.java:125)
        at com.android.chimpchat.core.ChimpImageBase.convertToBytes(ChimpImageBase.java:72)
        at com.android.monkeyrunner.MonkeyImage.convertToBytes(MonkeyImage.java:66)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)

java.lang.NullPointerException: java.lang.NullPointerException

171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at org.python.core.Py.JavaError(Py.java:495)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at org.python.core.Py.JavaError(Py.java:488)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:188)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at org.python.core.PyObject.__call__(PyObject.java:404)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at org.python.core.PyObject.__call__(PyObject.java:408)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at org.python.core.PyMethod.__call__(PyMethod.java:124)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at org.python.pycode._pyx0.main$1(D:\Web\wechat_automated_jump_game\monkeyrunner.py:26)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at org.python.pycode._pyx0.call_function(D:\Web\wechat_automated_jump_game\monkeyrunner.py)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at org.python.core.PyTableCode.call(PyTableCode.java:165)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at org.python.core.PyBaseCode.call(PyBaseCode.java:120)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at org.python.core.PyFunction.__call__(PyFunction.java:307)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at org.python.pycode._pyx0.f$0(D:\Web\wechat_automated_jump_game\monkeyrunner.py:67)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at org.python.pycode._pyx0.call_function(D:\Web\wechat_automated_jump_game\monkeyrunner.py)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at org.python.core.PyTableCode.call(PyTableCode.java:165)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at org.python.core.PyCode.call(PyCode.java:18)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at org.python.core.Py.runCode(Py.java:1275)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at org.python.core.__builtin__.execfile_flags(__builtin__.java:522)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:225)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at com.android.monkeyrunner.ScriptRunner.run(ScriptRunner.java:116)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at com.android.monkeyrunner.MonkeyRunnerStarter.run(MonkeyRunnerStarter.java:77)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at com.android.monkeyrunner.MonkeyRunnerStarter.main(MonkeyRunnerStarter.java:189)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]Caused by: java.lang.NullPointerException
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at com.android.chimpchat.adb.image.ImageUtils.convertImage(ImageUtils.java:47)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at com.android.chimpchat.adb.image.ImageUtils.convertImage(ImageUtils.java:63)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at com.android.chimpchat.adb.AdbChimpImage.createBufferedImage(AdbChimpImage.java:41)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at com.android.chimpchat.core.ChimpImageBase.getBufferedImage(ChimpImageBase.java:65)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at com.android.chimpchat.core.ChimpImageBase.convertSnapshot(ChimpImageBase.java:125)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at com.android.chimpchat.core.ChimpImageBase.convertToBytes(ChimpImageBase.java:72)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at com.android.monkeyrunner.MonkeyImage.convertToBytes(MonkeyImage.java:66)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at java.lang.reflect.Method.invoke(Unknown Source)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
171231 15:27:17.799:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions]       ... 19 more
```

**Comment by zhujunsan** [comment]
看到截图相似问题，应该是系统太新而ADB以及相关lib不够新的关系，我再研究研究
