### ISSUE TITLE
could not convert string to float

### ISSUE THREAD

**Issue by yuankaiJGH** [microdog/wechat_automated_jump_game#3]
Traceback (most recent call last):
  File "wda.py", line 105, in <module>
    main()
  File "wda.py", line 58, in main
    press_time_raw = float(res.content) / 1000.0
ValueError: could not convert string to float: {
  "value" : "Unhandled endpoint: \/ -- http:\/\/127.0.0.1:8100\/ with parameters {\n    wildcards =     (\n        \"\"\n    );\n}",
  "sessionId" : "0096483F-9F7A-4776-BD92-C86AD389DA6C",
  "status

**Comment by microdog** [comment]
The second parameter for `wda.py` is the url of solver server not WDA server which is `http://127.0.0.1:5000` by default.
